import type { TimelineState } from "../types";
import { getStateSummary, getTimelineEvents, getVisibleEventCount } from "./timelineModel";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: TimelineState, fileName = "timeline") : ExportPayload {
  return { fileName: `${fileName || "timeline"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: TimelineState) {
  const events = getTimelineEvents(state);
  const summary = getStateSummary(state);
  const visibleCount = getVisibleEventCount(state);

  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "const events = " + JSON.stringify(events, null, 2) + ";",
    "",
    "const summary = " + JSON.stringify(summary, null, 2) + ";",
    "",
    "export default function TimelineComponent() {",
    "  const visibleEvents = events.slice(0, " + visibleCount + ");",
    "  const isHorizontal = state.orientation === \"horizontal\";",
    "  const regionRole = state.role === \"list\" ? \"region\" : state.role;",
    "  const markerGlyph = state.markerStyle === \"dot\" ? \"\" : state.markerStyle === \"number\" ? null : \"ok\";",
    "",
    "  return (",
    "    <section",
    "      id={state.id}",
    "      role={regionRole}",
    "      aria-label={state.ariaLabel}",
    "      tabIndex={state.tabIndex}",
    "      data-timeline-orientation={state.orientation}",
    "      data-timeline-state={state.previewState}",
    "      style={{",
    "        width: state.width,",
    "        minHeight: state.height,",
    "        padding: state.padding,",
    "        borderRadius: state.radius,",
    "        border: state.borderWidth + \"px solid \" + state.border,",
    "        boxShadow: \"0 \" + Math.round(state.shadow / 3) + \"px \" + state.shadow + \"px rgba(0,0,0,.28)\",",
    "        background: state.background,",
    "        color: state.foreground,",
    "        fontFamily: state.fontFamily,",
    "        opacity: state.disabled ? 0.55 : 1,",
    "        display: \"grid\",",
    "        alignContent: \"start\",",
    "        gap: state.gap,",
    "      }}",
    "    >",
    "      <div style={{ display: \"grid\", gap: 8 }}>",
    "        <p style={{ margin: 0, color: state.accent, fontSize: 12, fontWeight: 700, letterSpacing: \"0.18em\", textTransform: \"uppercase\" }}>{summary.statusText}</p>",
    "        <h3 style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h3>",
    "        <p style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "      </div>",
    "      <ol",
    "        aria-label={state.title + \" events\"}",
    "        role=\"list\"",
    "        style={{",
    "          display: \"grid\",",
    "          gap: state.gap,",
    "          gridTemplateColumns: isHorizontal ? `repeat(${visibleEvents.length}, minmax(0, 1fr))` : undefined,",
    "          listStyle: \"none\",",
    "          margin: \"24px 0 0\",",
    "          padding: 0,",
    "        }}",
    "      >",
    "        {visibleEvents.map((event, index) => {",
    "          const isCurrent = event.status === \"current\";",
    "          const alignEnd = state.alternating && !isHorizontal && index % 2 === 1;",
    "          const markerText = markerGlyph === null ? String(index + 1) : markerGlyph;",
    "",
    "          return (",
    "            <li key={event.id} role=\"listitem\" aria-current={isCurrent ? \"step\" : undefined} style={{ display: \"grid\", justifyItems: alignEnd ? \"end\" : \"start\", textAlign: alignEnd ? \"right\" : \"left\" }}>",
    "              <article style={{ display: \"grid\", gap: 12, maxWidth: isHorizontal ? undefined : 544, height: isHorizontal ? \"100%\" : undefined, opacity: event.status === \"upcoming\" ? 0.72 : 1 }}>",
    "                <div style={{ display: \"grid\", gridTemplateColumns: \"auto 1fr\", alignItems: isHorizontal ? \"center\" : \"start\", gap: 12 }}>",
    "                  <span aria-hidden=\"true\" style={{ display: \"grid\", placeItems: \"center\", width: 36, height: 36, borderRadius: 999, border: \"1px solid \" + (isCurrent ? state.accent : state.border), background: isCurrent ? state.accent : \"transparent\", color: isCurrent ? \"#020617\" : state.foreground, fontSize: 12, fontWeight: 700 }}>{markerText}</span>",
    "                  <span aria-hidden=\"true\" style={{ width: isHorizontal ? \"100%\" : 1, height: isHorizontal ? 1 : 48, borderTop: isHorizontal ? \"1px \" + state.connectorStyle + \" \" + state.border : undefined, borderLeft: isHorizontal ? undefined : \"1px \" + state.connectorStyle + \" \" + state.border, opacity: index === visibleEvents.length - 1 ? 0 : 1 }} />",
    "                </div>",
    "                <div style={{ border: \"1px solid \" + (isCurrent ? state.accent : state.border), borderRadius: 20, padding: 16, background: isCurrent ? \"color-mix(in oklab, \" + state.accent + \" 14%, transparent)\" : \"transparent\" }}>",
    "                  {state.datePlacement === \"top\" && <time dateTime={event.date} style={{ color: state.accent, fontSize: 12, fontWeight: 700, letterSpacing: \"0.14em\", textTransform: \"uppercase\" }}>{event.displayDate}</time>}",
    "                  <div style={{ display: state.datePlacement === \"side\" ? \"flex\" : \"block\", alignItems: \"flex-start\", justifyContent: \"space-between\", gap: 12, marginTop: 8 }}>",
    "                    <h4 style={{ margin: 0, fontWeight: 700 }}>{event.title}</h4>",
    "                    {state.datePlacement === \"side\" && <time dateTime={event.date} style={{ flexShrink: 0, color: state.accent, fontSize: 12, fontWeight: 700, letterSpacing: \"0.14em\", textTransform: \"uppercase\" }}>{event.displayDate}</time>}",
    "                  </div>",
    "                  <p style={{ margin: \"4px 0 0\", color: state.muted, fontSize: 14 }}>{event.description}</p>",
    "                  <span style={{ display: \"inline-flex\", marginTop: 12, border: \"1px solid \" + (isCurrent ? state.accent : state.border), borderRadius: 999, padding: \"4px 10px\", color: isCurrent ? state.accent : state.muted, fontSize: 12, textTransform: \"capitalize\" }}>{event.status}</span>",
    "                </div>",
    "              </article>",
    "            </li>",
    "          );",
    "        })}",
    "      </ol>",
    "      {summary.hiddenCount > 0 && <p style={{ margin: \"16px 0 0\", color: state.muted, fontSize: 14 }}>{summary.hiddenCount} later events are collapsed in this state.</p>}",
    "      <p style={{ margin: \"16px 0 0\", color: state.muted, fontSize: 12 }}>{state.helper} - {state.previewState}</p>",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}
